spring:
  application:
    name: 'Forum'

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  datasource:
    url: jdbc:mysql://localhost:3306/forum
    username: ${username}
    password: ${password}

  jpa:
    generate-ddl: true
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${clientId}
            clientSecret: ${clientSecret}
            scope:
              - email
              - profile

  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${mailUsername}
    password: ${mailPassword}
    protocol: smtps

server:
  port: 8080

jwt:
  cookieName: jwtToken
  secret: ${secret}
  expiration: 86400

upload:
  path: ${path}

hostname: localhost:8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'